project:
  type: website
website:
  title: "Problemas resueltos de Álgebra Lineal"
  search: false
  site-url: https://pedritomelenas.github.io/CREPAL
  repo-url: https://github.com/pedritomelenas/CREPAL
  issue-url: https://github.com/pedritomelenas/CREPAL/issues
  navbar:
    right:
      - icon: github
        href: https://github.com/pedritomelenas/CREPAL
        aria-label: GitHub

  sidebar: 
    style: "docked"
    footer: Hecho con [Quarto](https://quarto.org/)
    contents:
      - text: "Matrices y sistemas de ecuaciones"
        href: "matrices-sistemas.md"
      - text: "Espacios vectoriales"
        href: "espacios-vectoriales.md"
      - text: "Aplicaciones lineales"
        href: "aplicaciones-lineales.md"
      - text: "Espacio euclídeo"
        href: "espacio-euclideo.md"
      - text: "Otros"
        href: "resueltos-examenes.md"

format:
  html:
    theme: flatly
    lang: es