project:
  type: website
website:
  title: "Problemas resueltos de Álgebra Lineal"
  search: false
  site-url: https://pedritomelenas.github.io/CREPAL
  repo-url: https://github.com/pedritomelenas/CREPAL
  navbar:
    right:
        - icon: github
          menu:
            - text: "Contribuir (código fuente)"
              href: https://github.com/pedritomelenas/CREPAL
              target: _blank
            - text: "Informar de un problema"
              href: https://github.com/pedritomelenas/CREPAL/issues
              target: _blank


  sidebar: 
    style: "docked"
    footer: Hecho con [Quarto](https://quarto.org/)
    contents:
      - text: "Sistemas de ecuaciones, matrices y determinantes"
        href: "matrices-sistemas.md"
      - text: "Espacios vectoriales"
        href: "espacios-vectoriales.md"
      - text: "Aplicaciones lineales"
        href: "aplicaciones-lineales.md"
      # - text: "Diagonalización por semejanza"  #Eva quiere añadir estas dos nuevas secciones, lo dejo preparado para solo descomentarlo si te parece bien así y aquí
      #   href: "diagonalizacion-semejanza.md"
      # - text: "Formas cuadráticas y diagonalización por congruencia"
      #   href: "formas-cuadraticas.md"
      - text: "Espacio euclídeo"
        href: "espacio-euclideo.md"
      - text: "Otros"
        href: "resueltos-examenes.md"


format:
  html:
    theme: 
      light: flatly
      dark: darkly 
    lang: es

